# Generated by Django 5.0.4 on 2024-05-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/cloth'),
        ),
    ]
