# Generated by Django 5.0.4 on 2024-05-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AlterModelOptions(
            name='addbooks',
            options={'verbose_name': 'книгу', 'verbose_name_plural': 'Список книг'},
        ),
    ]
