# Generated by Django 5.0.4 on 2024-05-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addbooks',
            options={'verbose_name': 'книги', 'verbose_name_plural': 'Список книг'},
        ),
        migrations.AlterField(
            model_name='addbooks',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/', verbose_name='Загрузите фото'),
        ),
    ]
